site_name: Tapioca-Wrapper
pages:
- Home: index.md
- About: about.md
- Quickstart: quickstart.md
- Available Flavours: flavours.md
- New Flavour: newflavour.md
- Contributors: contributors.md
- Changelog: changelog.md
theme: readthedocs
